"""initial

Revision ID: 06293ca0baf0
Revises:
Create Date: 2025-04-22 04:32:19.753261

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06293ca0baf0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("phone_hmac", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("phone_hmac"),
    )
    op.create_index(
        op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True
    )
    op.create_table(
        "favorites",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("self_rating", sa.INTEGER(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "self_rating >= 1 AND self_rating <= 10",
            name="check_self_rating_range",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "movie_id", name="unique_profile_movie"
        ),
    )
    op.create_index(
        op.f("ix_favorites_movie_id"), "favorites", ["movie_id"], unique=False
    )
    op.create_index(
        op.f("ix_favorites_profile_id"),
        "favorites",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 10", name="check_rating_range"
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "movie_id", name="unique_profile_movie_reviews"
        ),
    )
    op.create_index(
        op.f("ix_reviews_movie_id"), "reviews", ["movie_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_profile_id"), "reviews", ["profile_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_profile_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_movie_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_favorites_profile_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_movie_id"), table_name="favorites")
    op.drop_table("favorites")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
