"""profile_constraint

Revision ID: a7d0590542c6
Revises: b250cf8f0ad5
Create Date: 2025-04-18 07:34:10.999346

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7d0590542c6"
down_revision: Union[str, None] = "b250cf8f0ad5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "social_accounts", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "social_accounts", type_="unique")
    # ### end Alembic commands ###
